import { expect, test } from '@playwright/test'

test('weighted controls reach the API and export the displayed result without another solve', async ({ page }) => {
  await page.route('https://tile.openstreetmap.org/**', route => route.abort())
  await page.goto('/')
  await page.getByLabel('Saved dataset').selectOption('z-risk-demo')
  await page.getByLabel('Grid cell (m)', { exact: true }).fill('25')
  await page.getByRole('combobox', { name: 'Objective', exact: true }).selectOption('risk')
  await page.getByRole('combobox', { name: 'Algorithm', exact: true }).selectOption('dijkstra')
  await page.getByRole('combobox', { name: 'Objective', exact: true }).selectOption('risk')
  await page.getByLabel('Background score assumption').fill('0')
  await page.getByLabel('Safety distance (m)').fill('2')
  const generate = page.getByRole('button', { name: 'Generate route', exact: true })
  await expect(generate).toBeEnabled()
  let solves = 0
  page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/route')) solves++ })
  const response = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/route'))
  await generate.click()
  const shown = await (await response).json()
  await expect(page.getByTestId('route-result')).toContainText('Route found')
  await expect(page.getByTestId('route-result')).toContainText('exact: true')
  expect(shown.controls.safety_distance_m).toBe(2)
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export route GeoJSON' }).click()
  const stream = await (await event).createReadStream()
  const chunks = []
  for await (const chunk of stream!) chunks.push(chunk)
  const exported = JSON.parse(Buffer.concat(chunks).toString())
  expect(exported.features[0].geometry).toEqual(shown.geometry)
  expect(exported.metadata.runtime_ms).toBe(shown.runtime_ms)
  expect(exported.metadata.controls).toEqual(shown.controls)
  expect(solves).toBe(1)
  await page.getByLabel('Risk weight', { exact: true }).fill('0.8')
  await expect(page.getByTestId('route-result')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Export route GeoJSON' })).toBeDisabled()
})

test('ABIT* zero budget is explicit and exports no successful geometry', async ({ page }) => {
  await page.route('https://tile.openstreetmap.org/**', route => route.abort())
  await page.goto('/')
  await page.getByLabel('Saved dataset').selectOption('z-risk-demo')
  await page.getByRole('combobox', { name: 'Algorithm', exact: true }).selectOption('abitstar')
  await page.getByLabel('ABIT* search budget (s)').fill('0')
  const generate = page.getByRole('button', { name: 'Generate route', exact: true })
  await expect(generate).toBeEnabled()
  await generate.click()
  await expect(page.getByTestId('route-result')).toContainText('Timed out without exact route')
  await expect(page.getByTestId('route-result')).toContainText('exact: false')
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export route GeoJSON' }).click()
  const stream = await (await event).createReadStream()
  const chunks = []
  for await (const chunk of stream!) chunks.push(chunk)
  expect(JSON.parse(Buffer.concat(chunks).toString()).features).toEqual([])
})

test('comparison recomputes comparable costs and supports mobile and report export', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://tile.openstreetmap.org/**', route => route.abort())
  await page.goto('/')
  await page.getByLabel('Saved dataset').selectOption('z-risk-demo')
  await page.getByLabel('Grid cell (m)', { exact: true }).fill('25')
  await page.getByRole('combobox', { name: 'Objective', exact: true }).selectOption('risk')
  await page.getByLabel('Background score assumption').fill('0')
  await page.getByLabel('ABIT* repetitions').fill('1')
  await page.getByLabel('ABIT* search budget (s)').fill('0.5')
  const compare = page.getByRole('button', { name: 'Compare algorithms', exact: true })
  await expect(compare).toBeEnabled()
  await compare.click()
  const table = page.getByTestId('comparison-result')
  await expect(table).toContainText('distance A*')
  await expect(table).toContainText('weighted Dijkstra')
  await expect(table).toContainText('ABIT* run 1')
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export comparison', exact: true }).click()
  const stream = await (await event).createReadStream()
  const chunks = []
  for await (const chunk of stream!) chunks.push(chunk)
  const report = JSON.parse(Buffer.concat(chunks).toString())
  expect(report.runs).toHaveLength(4)
  expect(report.runs[0].comparison_costs.objective_cost).toBeGreaterThan(report.runs[1].comparison_costs.objective_cost)
  expect(report.runs[1].comparison_costs.status).toBe('verified')
  expect(report.runs[1].comparison_costs.objective_cost).toBeCloseTo(report.runs[2].comparison_costs.objective_cost)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('research mode explains readiness, exports assumptions and invalidates results on mode change', async ({ page }) => {
  await page.route('https://tile.openstreetmap.org/**', route => route.abort())
  await page.goto('/')
  await page.getByLabel('Saved dataset').selectOption('z-research-demo')
  await page.getByRole('combobox', { name: 'Algorithm', exact: true }).selectOption('abitstar')
  await page.getByLabel('ABIT* search budget (s)').fill('0')
  const generate = page.getByRole('button', { name: 'Generate route', exact: true })
  await expect(generate).toBeEnabled()
  await generate.click()
  await expect(page.getByTestId('route-result')).toContainText('Temporary restriction coverage unverified')
  await expect(page.getByTestId('route-result')).not.toContainText('Timed out')
  await page.getByRole('combobox', { name: 'Planning mode', exact: true }).selectOption('research')
  await expect(page.getByTestId('route-result')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Algorithm', exact: true }).selectOption('astar')
  await page.getByRole('combobox', { name: 'Objective', exact: true }).selectOption('risk')
  await page.getByLabel('Background score assumption').fill('0')
  await generate.click()
  await expect(page.getByTestId('route-result')).toContainText('Route found')
  await expect(page.getByTestId('route-result')).toContainText('constraint verification incomplete')
  await expect(page.getByTestId('route-result')).toContainText('Preparation:')
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export route GeoJSON' }).click()
  const stream = await (await event).createReadStream()
  const chunks = []
  for await (const chunk of stream!) chunks.push(chunk)
  const exported = JSON.parse(Buffer.concat(chunks).toString())
  expect(exported.metadata.planning_mode).toBe('research')
  expect(exported.metadata.research_assumptions.length).toBeGreaterThan(0)
  expect(exported.features).toHaveLength(1)
  await page.getByLabel('ABIT* repetitions').fill('1')
  const response = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/compare'))
  await page.getByRole('button', { name: 'Compare algorithms', exact: true }).click()
  const report = await (await response).json()
  expect(report.runs.every((run: { result: { planning_mode: string } }) => run.result.planning_mode === 'research')).toBe(true)
  await page.getByRole('combobox', { name: 'Planning mode', exact: true }).selectOption('strict')
  await expect(page.getByTestId('route-result')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Export route GeoJSON' })).toBeDisabled()
})
