import { expect, test } from '@playwright/test'

test('route success, exact selection, export, invalidation and explicit failure', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.route('https://tile.openstreetmap.org/**', (route) => route.abort())
  await page.goto('/')
  await page.getByLabel('Saved dataset').selectOption('z-routing-demo')
  const generate = page.getByRole('button', { name: 'Generate route', exact: true })
  const result = page.getByTestId('route-result')
  await expect(generate).toBeEnabled({ timeout: 15000 })
  await generate.click()
  await expect(result).toContainText('Route found')
  await expect(result).toContainText('276.222 m')
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export route GeoJSON' }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('z-routing-demo-route.geojson')
  const stream = await download.createReadStream()
  const chunks = []
  for await (const chunk of stream!) chunks.push(chunk)
  const exported = JSON.parse(Buffer.concat(chunks).toString())
  expect(exported.features[0].geometry.coordinates[0]).toEqual([10.5192, 52.2693])
  expect(exported.metadata.experiment.synthetic).toBe(true)
  await page.getByLabel('Grid cell (m)', { exact: true }).fill('200')
  await expect(result).toHaveCount(0)
  await expect(generate).toBeEnabled({ timeout: 15000 })
  await generate.click()
  await expect(result).toContainText('No path on this grid')
  await page.getByLabel('Grid cell (m)', { exact: true }).fill('50')
  await expect(generate).toBeEnabled({ timeout: 15000 })
  await page.getByLabel('start longitude', { exact: true }).fill('10.5193')
  await expect(result).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Export route GeoJSON' })).toBeDisabled()
  await generate.click()
  await expect(result).toContainText('Route found')
  await page.getByRole('button', { name: 'Select end on map' }).click()
  await expect(page.getByText('Click the map to choose end.', { exact: false })).toBeVisible()
  await page.getByRole('region', { name: 'Dataset map' }).click({ position: { x: 220, y: 220 } })
  await expect(result).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Cancel selection' })).toHaveCount(0)
  await page.getByLabel('Grid cell (m)', { exact: true }).fill('25')
  await expect(generate).toBeEnabled({ timeout: 15000 })
  await page.getByLabel('start longitude', { exact: true }).fill('0')
  await generate.click()
  await expect(result).toContainText('Invalid endpoint')
  await page.getByLabel('Saved dataset').selectOption('z-external-experiment')
  await expect(result).toHaveCount(0)
  await expect(generate).toBeEnabled({ timeout: 15000 })
  await generate.click()
  await expect(result).toContainText('Unresolved input')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
